name: other

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    if: "github.repository == 'BenjaminBossan/mops'"
    strategy:
      fail-fast: false  # need to see which ones fail
      matrix:
        os: [ubuntu-latest]
        python: ["3.9", "3.10"]

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        git log -n 3 --pretty
        printenv
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        echo "$(git log --format=%B -n 1 ${{github.event.after}})"
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        echo "Commit SHA: ${{github.event.after}}"
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        echo "commit message: ${{env.COMMIT_MESSAGE}} (or ${COMMIT_MESSAGE})"
        pip install .
        python --version
        pip --version
        pip list
      shell: bash

    - name: Tests
      run: |
        python -m pytest mops/
