name: Debugging mops install

on:
  - pull_request

jobs:
  run-debugging-steps-v3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: printenv
      run: printenv
    - name: Install mops and check location
      run: |
        pip --version
        pip install --no-cache-dir .
        pip list
        pwd
        which python
        which python3
        python3 --version
        echo "mops location when running from root"
        python3 -c "import mops;path=mops.__path__;print(path)"
        mkdir tmp
        cd tmp
        echo "mops location when not running from root"
        python3 -c "import mops;path=mops.__path__;print(path)"

  run-debugging-steps-v4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: printenv
      run: printenv
    - name: Install mops and check location
      run: |
        pip --version
        pip install --no-cache-dir .
        pip list
        pwd
        which python
        which python3
        python3 --version
        echo "mops location when running from root"
        python3 -c "import mops;path=mops.__path__;print(path)"
        mkdir tmp
        cd tmp
        echo "mops location when not running from root"
        python3 -c "import mops;path=mops.__path__;print(path)"
