name: pytest

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  has-it:

    runs-on: ${{ matrix.os }}
    if: ${{ (github.repository == 'BenjaminBossan/mops') && contains(github.event.head_commit.message, '[CI inference]') }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python: ["3.9", "3.10", "3.11", "3.12"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

  has-it-not:

    runs-on: ${{ matrix.os }}
    if: ${{ (github.repository == 'BenjaminBossan/mops') && !contains(github.event.head_commit.message, '[CI inference]') }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python: ["3.9", "3.10", "3.11", "3.12"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-13", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install setuptools transformers pytest
          pip install -e .
      - name: Test with pytest
        run: |
          pytest test.py --durations=99
